# Generated by Django 4.2.7 on 2023-11-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_question_type_question_required_file_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.choice'),
        ),
    ]
