# Generated by Django 4.2.7 on 2023-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_response_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
