# Generated by Django 4.2.7 on 2023-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TX', 'Short Text'), ('LT', 'Long Text'), ('CH', 'Choice'), ('EM', 'Email'), ('FL', 'File Upload')], default='TX', max_length=2),
        ),
    ]
