# Generated by Django 4.2.7 on 2023-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_multiple_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
