# Generated by Django 4.2.7 on 2023-11-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_question_file_format_question_max_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='multiple_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
