# Generated by Django 4.2.7 on 2023-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_choice_multiple_choices_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='multiple_choices',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
