# Generated by Django 4.2.7 on 2023-11-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_remove_choice_multiple_choices_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_file_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
