# Generated by Django 4.2.7 on 2023-11-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_question_max_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
