# Generated by Django 4.2.7 on 2023-11-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_question_max_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.CharField(default='value', max_length=200),
        ),
    ]
