# Generated by Django 4.2.7 on 2023-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_choice_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date_responded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
