# Generated by Django 4.2.7 on 2023-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_alter_response_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
