# Generated by Django 4.2.7 on 2023-11-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_alter_response_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='file',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='survey.response'),
        ),
    ]
