# Generated by Django 4.2.7 on 2023-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_survey_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
